### PR TITLE
Android Extensions: View holder pattern support and caching options

### PR DESCRIPTION
**Pull request by yanex**

### CODE REVIEW

**Comment by denis-trailin-hs** [comment]
👍

**Comment by Angryhead** [comment]
Showing my support for this!

**Comment by KasparPeterson** [comment]
Really nice idea!

**Comment by rongi** [comment]
There is already no need to write view holders with Kotlin etensions
http://stackoverflow.com/questions/33304570/kotlin-synthetic-in-adapter-or-viewholder

**Comment by yanex** [comment]
@rongi Well, such view holder will support caching functionality seamlessly.

**Comment by Judrummer** [comment]
Agree with you too!!

**Comment by Wavesonics** [comment]
Without something like this we'd either be forced to use android extensions at the fragment level and something like Kotterknife at the ViewHolder level, or, more likely, just use KotterKnife everywhere.

**Comment by szymenpl** [comment]
Anyone knows when caching in custom views and viewholders will be available? Or maybe what is reason for method `public View _$_findCachedViewById(int var1)`, which is generated in custom view, but not used. (`findViewById` is always used)

**Comment by 06needhamt** [comment]
👍

**Comment by neiljaywarner** [comment]
(thumbsup)

**Comment by rongi** [comment]
👍

**Comment by neiljaywarner** [comment]
(thumbsup)

**Comment by neiljaywarner** [comment]
When is this going to be production ready?

**Comment by vkotovv** [comment]
@yanex Is it still experimental?

**Pull request merged**
